import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {decode as base64_decode, encode as base64_encode} from 'base-64';
import IONequiToken from '../business/ioToken';
import { useEffect } from 'react';
import qrCode from '../business/qrCode';
import { Layout } from '../components/Layout';
import Cookies from 'universal-cookie';
import { useRouter } from 'next/router';
import { Button, Card, CardBody, CardFooter, CardHeader, CardText, CardTitle } from 'reactstrap';

const cookies=new Cookies;
export default function Home() {
  const id='12abcmt5gdk5bvsfbo7catg4k6';
  const client='1e0ab7h5s689rnjkkb39ile9obt77vgo99vagvenqmbafbs88gul'
  var ty=base64_encode('12abcmt5gdk5bvsfbo7catg4k6:1e0ab7h5s689rnjkkb39ile9obt77vgo99vagvenqmbafbs88gul');
  console.log(ty)
  const flujocompleto=async()=>{
    // const responseToken=await IONequiToken.post();
    // const toke=responseToken.access_token;
    // console.log('token',toke)
    // const responseCode=await qrCode.fetchGenerateCodeQR(toke,'1')
    // console.log(responseCode.ResponseMessage.ResponseHeader.Status)
    const merchant=cookies.get('code');
    console.log(merchant)
    const lista=await qrCode.fetchListLogsNequi(merchant)
    console.log(lista)
  }
  useEffect(() => {
    flujocompleto()
  }, [])

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='row d-flex justify-content-center mt-5'>
        <div className='col-5'>
          <Card className='mb-5'>
              <CardHeader>
                Header
              </CardHeader>
              <CardBody>
                <CardTitle tag="h5">
                  Special Title Treatment
                </CardTitle>
                <CardText>
                  With supporting text below as a natural lead-in to additional content.
                </CardText>
                <Button>
                  Go somewhere
                </Button>
              </CardBody>
              <CardFooter>
                Footer
              </CardFooter>
            </Card>
          </div>
      </div>
    </Layout>
  )
}
